version: '3.0'
services:
  mysql:
    container_name: booking-mysql
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "booking"
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql:/var/lib/mysql

  zookeeper:
    container_name: booking-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: booking-kafka
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

  booking:
    container_name: booking
    image: om/booking:latest
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - OPS=test
    depends_on:
      - mysql
      - kafka
    network_mode: host

volumes:
  mysql:
    driver: local
