service:
  user:
    baseurl: http://localhost:6009
  gateway:
    baseurl: http://localhost:6008

server:
  port: 6007

# Database Firebase
firebase:
  service-account-filename: classpath:firebase-service-accounts.json
  realtime-database-url: https://learne-bfb9c-default-rtdb.asia-southeast1.firebasedatabase.app

app:
  name: service-auth