spring:
  datasource:
    url: mysql://nrkgklvcruf1lxyz:d16m1b3oo84mplbt@migae5o25m2psr4q.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/m4s79dyh4tj03mmp
    username: nrkgklvcruf1lxyz
    password: d16m1b3oo84mplbt
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  name: service-user
