app:
  name: service-course

spring:
  datasource:
    url: jdbc:postgresql://ec2-44-209-24-62.compute-1.amazonaws.com:5432/d5n7pg3io17ktp
    username: tcdtbzhwzhgcdf
    password: 1a3fac565bb99232c01c52f0c33afa232e307675c9bb0fa6fceb5aeb67639429
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

service:
  question-bank:
    baseurl: https://learnequestionbank.herokuapp.com
  user:
    baseurl: https://learneuser.herokuapp.com