spring:
  datasource:
    url: jdbc:postgresql://ec2-23-21-207-93.compute-1.amazonaws.com:5432/df1c7fnf0g7h6f
    username: eptmywlpphtiak
    password: e3d22d4b39073ff5a2cb772446aa9bb207797382d1743ab4d75ad62dbba1e8f7
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  name: service-user
