spring:
  datasource:
    url: jdbc:postgresql://ec2-100-26-39-41.compute-1.amazonaws.com:5432/dfadjkel9cmlon
    username: udfrqepeatccsz
    password: 888e21a53fe51002291372304ecd137a1fdc1b533006a3ab8d91f3349d6d2326
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  name: service-questions-bank


service:
  user:
    baseurl: https://learneuser.herokuapp.com
  gateway:
    baseurl: https://learnegateway.herokuapp.com
  question-bank:
    baseurl: https://learnequestionbank.herokuapp.com
  course:
    baseurl: https://learnecourse.herokuapp.com
  studyset:
    baseurl: https://learnestudyset.herokuapp.com
  multimedia:
    baseurl: https://learnemultimedia.herokuapp.com