service:
  user:
    baseurl: https://learneuser.herokuapp.com
  gateway:
    baseurl: https://learnegateway.herokuapp.com
  question-bank:
    baseurl: https://learnequestionbank.herokuapp.com
  course:
    baseurl: https://learnecourse.herokuapp.com
  studyset:
    baseurl: https://learnestudyset.herokuapp.com
# Database Firebase
firebase:
  service-account-filename: classpath:firebase-service-accounts.json
  realtime-database-url: https://learne-41d47-default-rtdb.asia-southeast1.firebasedatabase.app

app:
  name: multimedia

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB