spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_9caa7b1e5bc1e22
    username: b0058c55ccf627
    password: d5d8ad53
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl