app:
  name: service-course

spring:
  datasource:
    url: mysql://o1phhfb5paah5n4c:cgfp5hatumtevwdd@r98du2bxwqkq3shg.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/wenf20llniwlmley
    username: o1phhfb5paah5n4c
    password: cgfp5hatumtevwdd
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

service:
  question-bank:
    baseurl: https://learnequestionbank.herokuapp.com
  user:
    baseurl: https://learneuser.herokuapp.com