service:
  user:
    baseurl: https://learneserviceuser.herokuapp.com
  gateway:
    baseurl: https://learneservicegateway.herokuapp.com
  question-bank:
    baseurl: https://learneservicequestionbank.herokuapp.com
  course:
    baseurl: https://learneservicecourse.herokuapp.com
# Database Firebase
firebase:
  service-account-filename: classpath:firebase-service-accounts.json
  realtime-database-url: https://learne-bfb9c-default-rtdb.asia-southeast1.firebasedatabase.app

app:
  name: service-auth