spring:
  datasource:
    url: jdbc:postgresql://ec2-44-206-89-185.compute-1.amazonaws.com:5432/db0pt7meirvfkq
    username: dbbhwsrxdjgxhx
    password: ebd5cd30243605c7269b37648d48f2d95aac2ca6589b2414c144c6f984013f48
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  name: service-studyset