service:
  user:
    baseurl: https://learneuser.herokuapp.com
  gateway:
    baseurl: https://learnegateway.herokuapp.com
  question-bank:
    baseurl: https://learnequestionbank.herokuapp.com
  course:
    baseurl: http://localhost:6013
# Database Firebase
firebase:
  service-account-filename: classpath:firebase-service-accounts.json
  realtime-database-url: https://learne-bfb9c-default-rtdb.asia-southeast1.firebasedatabase.app

app:
  name: service-auth