spring:
  datasource:
    url: mysql://g39kxfw8slb1lqys:flwnpr07fes0vxun@qvti2nukhfiig51b.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/x11et4g32hgrabsr
    username: g39kxfw8slb1lqys
    password: flwnpr07fes0vxun
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  name: service-questions-bank