app:
  name: service-course

service:
  question-bank:
    baseurl: https://learneservicequestionbank.herokuapp.com
  user:
    baseurl: https://learneserviceuser.herokuapp.com

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learne-service-course
    username: root
    password: root

#    sql:
#      init:
#        mode: always

  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
    hibernate:
#      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
server:
  port: 6013