spring:
  server:
    port: 8080

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

  jackson:
    default-property-inclusion: non_absent
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
      FLUSH_AFTER_WRITE_VALUE: true
    generator:
      FLUSH_PASSED_TO_STREAM: false
    deserialization:
      ACCEPT_FLOAT_AS_INT: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false

  kafka:
    consumer:
      group-id: om-hack2hire-booking-accepted
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  profiles:
    active: ${om.env:local}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

info.build:
  version: @project.version@

logging:
  level:
    org.apache.kafka: error